### ISSUE TITLE
Crash after selecting image from media browser

### ISSUE THREAD

**Issue by shivanshs9** [checkin-team/Checkin-Android#69]
Crash logs:
> Caused by java.lang.IllegalArgumentException: filename cannot be null
       at android.media.ExifInterface.<init>(ExifInterface.java:1328)
       at com.checkin.app.checkin.Utility.Utils.modifyOrientation(Utils.java:498)
       at com.checkin.app.checkin.misc.activities.SelectCropImageActivity.onActivityResult(SelectCropImageActivity.java:131)
       at android.app.Activity.dispatchActivityResult(Activity.java:7584)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4634)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:4683)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:113)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:71)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2023)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:224)
       at android.app.ActivityThread.main(ActivityThread.java:7060)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:536)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:928)

Relevant code:
https://github.com/checkin-team/Checkin-Android/blob/feedd91204b03aa8a4581da9388bf435416c9661/app/src/main/java/com/checkin/app/checkin/misc/activities/SelectCropImageActivity.java#L130-L131

**Comment by shivanshs9** [comment]
Use this - https://gist.github.com/tatocaster/32aad15f6e0c50311626
